var GAME_LEVELS = [
  [
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                    xxxxx                                          ",
   "                          o                                         xx!xx                                          ",
   "                                                                    xx!xx                                          ",
   "                          x                                           v                                            ",
   "                      o       o                                                                                    ",
   "                                                                                                                   ",
   "                     xxx     xxx                                             o                                     ",
   "                                                                           xxxxx                                   ",
   "                                       o  o  o  o                          xxxxx                  o                ",
   "    @                                                                      xxxxx                  o                ",
   "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxx     xxxxxx",
   "         x!!!x                           xx!!!xx                                         x!!!!x             xx!!!x ",
   "         x!!!x                           xx!!!xx                                         x!!!!x            xxx!!!x ",
   "         xxxxx                           xxvvvxx                                         xxxxxx           xxxx!!!x ",
   "                                                                                                         xxxxx!!!x ",
   "        o                                                             ooo                               xxxxxx!!!x ",
   "                                                                      oo                               xxxxxxx!!!x ",
   "     o                                                                                                xxxxxxxx!!!x ",
   "                                                                                                     xxxxxxxxx!!!x ", 
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",

  ],
  [
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                     x          x                                             ",
   "                                                                                    x!x        x!x                                            ",
   "                                                                  xxx                v     o    v    o                       xxx              ",
   "                                                   xx      xx    xx!xx                                                      xx!xx             ",
   "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!x             ",
   "                                                                 xxvxx                                                      xxvxx             ",
   "                                   xxxxx                                            xxx        xxx       xxx           xxx                    ",
   "                                                                                                                                              ",
   "                                          o o                                                                                x x            o ",
   "                        o                                                                                         xxx        x x            x ",
   "                                         xxxxx                            o    xxxxxxx                                      xx xx          xx ",
   "             xxxx       o       o                                              x     x        o        o                                  xxx ",
   "     @       x  x                                                xxxxx         x     x                           x!!!x                   xxxx ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxx",
   "                              x   x                  x     x                                                              x!!!!!!x!!!!!xxxxxxx",
   "                              x!!!x                  x!!!!!x                                                              x!!!!!!x!!!!!!!!!!!x",
   "                              x!!!x                  x!!!!!x                                                              x!!!!!!x!!!!!!!!!!!x",
   "                              xxxxx                  xxxxxxx                                                              xxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                "
],
[
 "                                                                                                     x!!!x                               ",
 "                                                                                                     xvvvx                               ",
 "                                                                                                                                         ",
 "                                                                                                                              oooo       ",
 "                                                                                                     xxxxx                    oooo       ",
 "                                                                 xxx                                                                          ",
 "         xxx                                                xxx                   xxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",
 "        xx!xx                                            xxx                     xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",
 "        xx!xx                                         xxxxx                     xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",                                                              
 "          v                                     xxxxx                          xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",                                                              
 "                                                                              xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",                                                              
 "                                     o      xxx                              xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",                                                              
 "          @                                                                 xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",                                                              
 " xxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                                                               
 "                 x!!!!x                              x!!!!!!!!!!!!!!!!!!x                                                                ",                                                           
 "                 x!!!!x                              x!!!!!!!!!!!!!!!!!!x                                                                ", 
 "                 xxxxxx                              x!!!!!!!!!!!!!!!!!!x                                                                ", 
 "                                                     xxxxxxxxxxxxxxxxxxxx                                                                ", 
 "                                                                                                                                         ", 
]
];                                                                                                          